#!/usr/bin/env bash
# dock2flox TOML emitter
# Reads the intermediate representation and produces a valid manifest.toml

# Requires: lib/core.sh sourced first

emit_toml() {
    local ir_file="$1"

    _emit_header
    _emit_install_section "$ir_file"
    _emit_vars_section "$ir_file"
    _emit_hook_section "$ir_file"
    _emit_services_section "$ir_file"
    _emit_options_section
}

# --- TOML escaping ---

# Escape a value for use in a TOML basic string (double-quoted)
_toml_escape() {
    local value="$1"
    # Must escape backslashes first, then other chars
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    value="${value//$'\t'/\\t}"
    value="${value//$'\r'/\\r}"
    # If value contains newlines, caller should use multi-line literal instead
    printf '%s' "$value"
}

# --- Section emitters ---

_emit_header() {
    cat <<'EOF'
# Generated by dock2flox — https://github.com/flox/dock2flox
# Review all entries marked with REVIEW or UNMAPPED before activating.
# Flox manifest version managed by Flox CLI
schema-version = "1.11.0"

EOF
}

_emit_install_section() {
    local ir_file="$1"

    # Collect INSTALL records, deduplicate by install_id (keep highest confidence)
    local deduped
    deduped=$(dock2flox_mktemp)

    # Sort by install_id, then by confidence (EXACT > HIGH > LOW > UNMAPPED)
    { grep "^INSTALL${IR_DELIM}" "$ir_file" 2>/dev/null || true; } | sort -t "$IR_DELIM" -k2,2 -k6,6 | \
        awk -F "$IR_DELIM" '!seen[$2]++' > "$deduped"

    if [[ ! -s "$deduped" ]]; then
        printf '[install]\n\n'
        return 0
    fi

    printf '[install]\n'

    while IFS="$IR_DELIM" read -r _ install_id pkg_path version pkg_group confidence line_num notes; do
        # Decode notes
        notes=$(_ir_decode "$notes")

        # Emit confidence-based comments for non-EXACT entries
        case "$confidence" in
            UNMAPPED)
                printf '# UNMAPPED: %s (line %s) — verify with: flox search %s\n' \
                    "${notes:-$pkg_path}" "$line_num" "$pkg_path"
                printf '# %s.pkg-path = "%s"\n' "$install_id" "$(_toml_escape "$pkg_path")"
                ;;
            LOW)
                printf '# REVIEW: %s (line %s)\n' "${notes:-$pkg_path}" "$line_num"
                printf '%s.pkg-path = "%s"\n' "$install_id" "$(_toml_escape "$pkg_path")"
                [[ -n "$version" ]] && printf '%s.version = "%s"\n' "$install_id" "$(_toml_escape "$version")"
                [[ -n "$pkg_group" ]] && printf '%s.pkg-group = "%s"\n' "$install_id" "$(_toml_escape "$pkg_group")"
                ;;
            HIGH)
                if [[ -n "$notes" ]]; then
                    printf '# %s\n' "$notes"
                fi
                printf '%s.pkg-path = "%s"\n' "$install_id" "$(_toml_escape "$pkg_path")"
                [[ -n "$version" ]] && printf '%s.version = "%s"\n' "$install_id" "$(_toml_escape "$version")"
                [[ -n "$pkg_group" ]] && printf '%s.pkg-group = "%s"\n' "$install_id" "$(_toml_escape "$pkg_group")"
                ;;
            EXACT|*)
                if [[ -n "$notes" && "$notes" != "from base image"* ]]; then
                    printf '# %s\n' "$notes"
                fi
                printf '%s.pkg-path = "%s"\n' "$install_id" "$(_toml_escape "$pkg_path")"
                [[ -n "$version" ]] && printf '%s.version = "%s"\n' "$install_id" "$(_toml_escape "$version")"
                [[ -n "$pkg_group" ]] && printf '%s.pkg-group = "%s"\n' "$install_id" "$(_toml_escape "$pkg_group")"
                ;;
        esac
    done < "$deduped"

    printf '\n'
}

_emit_vars_section() {
    local ir_file="$1"

    local vars
    vars=$({ grep "^VAR${IR_DELIM}" "$ir_file" 2>/dev/null || true; } | sort -t "$IR_DELIM" -k2,2 -u)

    if [[ -z "$vars" ]]; then
        printf '[vars]\n\n'
        return 0
    fi

    printf '[vars]\n'

    while IFS="$IR_DELIM" read -r _ name value line_num; do
        value=$(_ir_decode "$value")
        # Check if value contains newlines (shouldn't in [vars], but be safe)
        if [[ "$value" == *$'\n'* ]]; then
            # Use TOML multi-line literal string (no escaping needed inside ''')
            printf "%s = '''\n%s\n'''\n" "$name" "$value"
        else
            printf '%s = "%s"\n' "$name" "$(_toml_escape "$value")"
        fi
    done <<< "$vars"

    printf '\n'
}

_emit_hook_section() {
    local ir_file="$1"

    local hooks
    hooks=$({ grep "^HOOK${IR_DELIM}" "$ir_file" 2>/dev/null || true; } | sort -t "$IR_DELIM" -k2,2n)

    if [[ -z "$hooks" ]]; then
        printf '[hook]\n\n'
        return 0
    fi

    printf '[hook]\n'
    printf "on-activate = '''\n"

    # Emit structured hook content
    local has_env_exports=0

    # First pass: env exports (order 0xx)
    while IFS="$IR_DELIM" read -r _ order bash_line line_num; do
        bash_line=$(_ir_decode "$bash_line")
        if [[ "$order" -lt 100 ]]; then
            printf '%s\n' "$bash_line"
            has_env_exports=1
        fi
    done <<< "$hooks"

    [[ "$has_env_exports" -eq 1 ]] && printf '\n'

    # Second pass: setup commands and pip/npm comments (order 1xx+)
    while IFS="$IR_DELIM" read -r _ order bash_line line_num; do
        bash_line=$(_ir_decode "$bash_line")
        if [[ "$order" -ge 100 ]]; then
            printf '%s\n' "$bash_line"
        fi
    done <<< "$hooks"

    # Add standard return-to-project
    printf '\ncd "$FLOX_ENV_PROJECT"\n'
    printf "'''\n\n"
}

_emit_services_section() {
    local ir_file="$1"

    local services
    services=$({ grep "^SERVICE${IR_DELIM}" "$ir_file" 2>/dev/null || true; })

    if [[ -z "$services" ]]; then
        printf '[services]\n\n'
        return 0
    fi

    printf '[services]\n'

    while IFS="$IR_DELIM" read -r _ name command line_num; do
        command=$(_ir_decode "$command")
        # Always use multi-line literal for service commands (safe, no escaping needed)
        printf "%s.command = '''\n%s\n'''\n" "$name" "$command"
    done <<< "$services"

    printf '\n'
}

_emit_options_section() {
    cat <<'EOF'
[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
EOF
}
