#!/usr/bin/env bash
# dock2flox TOML emitter
# Reads the intermediate representation and produces a valid manifest.toml

# Requires: lib/core.sh sourced first

emit_toml() {
    local ir_file="$1"

    # Infer cache hooks based on detected packages (before emitting)
    _infer_cache_hooks "$ir_file"

    _emit_header
    _emit_install_section "$ir_file"
    _emit_vars_section "$ir_file"
    _emit_hook_section "$ir_file"
    _emit_services_section "$ir_file"
    _emit_options_section
}

# --- TOML escaping ---

# Escape a value for use in a TOML basic string (double-quoted)
_toml_escape() {
    local value="$1"
    # Must escape backslashes first, then other chars
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    value="${value//$'\t'/\\t}"
    value="${value//$'\r'/\\r}"
    # If value contains newlines, caller should use multi-line literal instead
    printf '%s' "$value"
}

# --- Cache hook inference ---

_infer_cache_hooks() {
    local ir_file="$1"
    local cache_map="$DOCK2FLOX_DATA/cache_hooks.map"

    [[ ! -f "$cache_map" ]] && return 0

    # Guard: don't inject if already done (idempotency)
    if { grep "^HOOK${IR_DELIM}" "$ir_file" 2>/dev/null || true; } | grep -q "FLOX_ENV_CACHE"; then
        return 0
    fi

    # Detect which ecosystems are present in INSTALL records
    local installs
    installs=$({ grep "^INSTALL${IR_DELIM}" "$ir_file" 2>/dev/null || true; })
    [[ -z "$installs" ]] && return 0

    local -A ecosystems_detected=()

    # Check for python
    if echo "$installs" | grep -q "python"; then
        ecosystems_detected[python]=1
    fi
    # Check for nodejs
    if echo "$installs" | grep -q "nodejs\|node"; then
        ecosystems_detected[nodejs]=1
    fi
    # Check for rust
    if echo "$installs" | grep -q "rustc\|cargo"; then
        ecosystems_detected[rust]=1
    fi
    # Check for go (exact match using delimiters to avoid matching "mongo", "golang" etc.)
    if echo "$installs" | grep -q "${IR_DELIM}go${IR_DELIM}"; then
        ecosystems_detected[go]=1
    fi

    [[ ${#ecosystems_detected[@]} -eq 0 ]] && return 0

    # Collect cache export lines for detected ecosystems
    local -a cache_exports=()
    local -a cache_dirs=()

    local ecosystem export_line
    while IFS=$'\t' read -r ecosystem export_line; do
        [[ -z "$ecosystem" || "$ecosystem" == "#"* ]] && continue
        if [[ -n "${ecosystems_detected[$ecosystem]:-}" ]]; then
            cache_exports+=("$export_line")
            # Extract dir path for mkdir
            local dir_path
            dir_path=$(echo "$export_line" | sed -E 's/.*="([^"]+)".*/\1/')
            cache_dirs+=("$dir_path")
        fi
    done < "$cache_map"

    [[ ${#cache_exports[@]} -eq 0 ]] && return 0

    # Inject cache hooks at priority 010-019 (before any user hooks)
    local i=10
    for export_line in "${cache_exports[@]}"; do
        ir_hook "$ir_file" "$(printf '%03d' $i)" "$export_line" "0"
        i=$((i + 1))
    done

    # Add mkdir -p for all cache dirs
    local mkdir_line="mkdir -p"
    for dir in "${cache_dirs[@]}"; do
        mkdir_line+=" \"$dir\""
    done
    ir_hook "$ir_file" "$(printf '%03d' $i)" "$mkdir_line" "0"

    log_verbose "Injected cache hooks for: ${!ecosystems_detected[*]}"
}

# --- Section emitters ---

_emit_header() {
    cat <<'EOF'
# Generated by dock2flox — https://github.com/flox/dock2flox
# Review all entries marked with REVIEW or UNMAPPED before activating.
# Flox manifest version managed by Flox CLI
schema-version = "1.11.0"

EOF
}

_emit_install_section() {
    local ir_file="$1"

    # Collect INSTALL records, deduplicate by install_id (keep highest confidence)
    local deduped
    deduped=$(dock2flox_mktemp)

    # Sort by install_id, then by confidence (EXACT > HIGH > LOW > UNMAPPED)
    { grep "^INSTALL${IR_DELIM}" "$ir_file" 2>/dev/null || true; } | sort -t "$IR_DELIM" -k2,2 -k6,6 | \
        awk -F "$IR_DELIM" '!seen[$2]++' > "$deduped"

    if [[ ! -s "$deduped" ]]; then
        printf '[install]\n\n'
        return 0
    fi

    printf '[install]\n'

    while IFS="$IR_DELIM" read -r _ install_id pkg_path version pkg_group confidence line_num notes; do
        # Decode notes
        notes=$(_ir_decode "$notes")

        # Emit confidence-based comments for non-EXACT entries
        case "$confidence" in
            UNMAPPED)
                printf '# UNMAPPED: %s (line %s) — verify with: flox search %s\n' \
                    "${notes:-$pkg_path}" "$line_num" "$pkg_path"
                printf '# %s.pkg-path = "%s"\n' "$install_id" "$(_toml_escape "$pkg_path")"
                ;;
            LOW)
                printf '# REVIEW: %s (line %s)\n' "${notes:-$pkg_path}" "$line_num"
                printf '%s.pkg-path = "%s"\n' "$install_id" "$(_toml_escape "$pkg_path")"
                [[ -n "$version" ]] && printf '%s.version = "%s"\n' "$install_id" "$(_toml_escape "$version")"
                [[ -n "$pkg_group" ]] && printf '%s.pkg-group = "%s"\n' "$install_id" "$(_toml_escape "$pkg_group")"
                ;;
            HIGH)
                if [[ -n "$notes" ]]; then
                    printf '# %s\n' "$notes"
                fi
                printf '%s.pkg-path = "%s"\n' "$install_id" "$(_toml_escape "$pkg_path")"
                [[ -n "$version" ]] && printf '%s.version = "%s"\n' "$install_id" "$(_toml_escape "$version")"
                [[ -n "$pkg_group" ]] && printf '%s.pkg-group = "%s"\n' "$install_id" "$(_toml_escape "$pkg_group")"
                ;;
            EXACT|*)
                if [[ -n "$notes" && "$notes" != "from base image"* ]]; then
                    printf '# %s\n' "$notes"
                fi
                printf '%s.pkg-path = "%s"\n' "$install_id" "$(_toml_escape "$pkg_path")"
                [[ -n "$version" ]] && printf '%s.version = "%s"\n' "$install_id" "$(_toml_escape "$version")"
                [[ -n "$pkg_group" ]] && printf '%s.pkg-group = "%s"\n' "$install_id" "$(_toml_escape "$pkg_group")"
                ;;
        esac
    done < "$deduped"

    printf '\n'
}

_emit_vars_section() {
    local ir_file="$1"

    local vars
    vars=$({ grep "^VAR${IR_DELIM}" "$ir_file" 2>/dev/null || true; } | sort -t "$IR_DELIM" -k2,2 -u)

    if [[ -z "$vars" ]]; then
        printf '[vars]\n\n'
        return 0
    fi

    printf '[vars]\n'

    while IFS="$IR_DELIM" read -r _ name value line_num; do
        value=$(_ir_decode "$value")
        # Check if value contains newlines (shouldn't in [vars], but be safe)
        if [[ "$value" == *$'\n'* ]]; then
            # Use TOML multi-line literal string (no escaping needed inside ''')
            printf "%s = '''\n%s\n'''\n" "$name" "$value"
        else
            printf '%s = "%s"\n' "$name" "$(_toml_escape "$value")"
        fi
    done <<< "$vars"

    printf '\n'
}

_emit_hook_section() {
    local ir_file="$1"

    local hooks
    hooks=$({ grep "^HOOK${IR_DELIM}" "$ir_file" 2>/dev/null || true; } | sort -t "$IR_DELIM" -k2,2n)

    if [[ -z "$hooks" ]]; then
        printf '[hook]\n\n'
        return 0
    fi

    printf '[hook]\n'
    printf "on-activate = '''\n"

    # Emit structured hook content
    local has_env_exports=0

    # First pass: env exports (order 0xx)
    while IFS="$IR_DELIM" read -r _ order bash_line line_num; do
        bash_line=$(_ir_decode "$bash_line")
        if [[ "$order" -lt 100 ]]; then
            printf '%s\n' "$bash_line"
            has_env_exports=1
        fi
    done <<< "$hooks"

    [[ "$has_env_exports" -eq 1 ]] && printf '\n'

    # Second pass: setup commands and pip/npm comments (order 1xx+)
    while IFS="$IR_DELIM" read -r _ order bash_line line_num; do
        bash_line=$(_ir_decode "$bash_line")
        if [[ "$order" -ge 100 ]]; then
            printf '%s\n' "$bash_line"
        fi
    done <<< "$hooks"

    # Add standard return-to-project
    printf '\ncd "$FLOX_ENV_PROJECT"\n'
    printf "'''\n\n"
}

_emit_services_section() {
    local ir_file="$1"

    local services
    services=$({ grep "^SERVICE${IR_DELIM}" "$ir_file" 2>/dev/null || true; })

    if [[ -z "$services" ]]; then
        printf '[services]\n\n'
        return 0
    fi

    printf '[services]\n'

    while IFS="$IR_DELIM" read -r _ name command line_num; do
        command=$(_ir_decode "$command")
        # Always use multi-line literal for service commands (safe, no escaping needed)
        printf "%s.command = '''\n%s\n'''\n" "$name" "$command"
    done <<< "$services"

    printf '\n'
}

_emit_options_section() {
    cat <<'EOF'
[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
EOF
}
