schema-version = "1.11.0"

[install]
bash.pkg-path = "bash"
coreutils.pkg-path = "coreutils"
gnugrep.pkg-path = "gnugrep"
gnused.pkg-path = "gnused"
gawk.pkg-path = "gawk"
python3.pkg-path = "python3"
pyyaml.pkg-path = "python313Packages.pyyaml"

[include]
environments = [
    { remote = "flox/colima" },
]

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]

