FROM debian:bookworm

RUN case "$(uname -m)" in \
      x86_64) apt-get install -y curl ;; \
      aarch64) apt-get install -y git ;; \
    esac

RUN <<EOF_HEREDOC
pkgs="wget"
for p in $pkgs; do
  apt-get install -y "$p"
done
if [[ -f /etc/debian_version ]]; then
  apt-get install -y ca-certificates
fi
EOF_HEREDOC

RUN if command -v not-a-real-manager; then apt-get install -y jq; fi
