FROM node:20-bookworm

ENV POETRY_HOME=/usr/local

RUN npm install -g corepack
RUN corepack enable yarn
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -e .
RUN curl -fsSL https://install.python-poetry.org | python3 - && \
    curl -fsSL https://sh.rustup.rs | sh -s -- -y; \
    corepack enable pnpm
